# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04a953df4901bbc355bcc3e663d41d35a8dcd8e31cd5fc955be8197fbb30d6e03ca55a73d54aa5fa622f5e8518c2775cc832e2aa54ca685fbd3c4117a7ee5833

test:
  secret_key_base: eb8fada7959e41c1e2fec1343b1bb868643fd771527015d68125f9eb4c8203eaba84116ba359f46959180242a9f07f93be476cd01d0625e53bfabd72ab8583d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
